### ISSUE TITLE
luaposix-5.1.8.tar.bz2找不到了

### ISSUE THREAD

**Issue by Rming** [lanrenwo/icombo#1]
文档中的下载路径失效，目前我正准备使用

https://luaposix.github.io/luaposix/index.html

替换

**Comment by lanrenwo** [comment]
感谢试用，我刚刚把文件，上传至博客上，你可以下载：
http://www.hongfanqu.com/upload/luaposix-5.1.8.tar.bz2

**Comment by Rming** [comment]
thx
